# Validate host settings independently of downloading the native SDK.
foreach(setting WINDOWS_UPDATE_URL UPDATE_PACKAGE_ID)
  if(NOT DEFINED DESKUP_${setting})
    set(DESKUP_${setting} "")
  endif()
endforeach()
if(NOT DEFINED DESKUP_WINDOWS_UPDATE_SOURCE)
  set(DESKUP_WINDOWS_UPDATE_SOURCE "")
endif()
if((DESKUP_WINDOWS_UPDATE_URL OR DESKUP_WINDOWS_UPDATE_SOURCE) AND NOT DESKUP_WINDOWS_UPDATE_SOURCE MATCHES "^(web|gitea)$")
  message(FATAL_ERROR "DESKUP_WINDOWS_UPDATE_SOURCE must be web or gitea")
endif()
set(DESKUP_SOURCE_GITEA 0)
if(DESKUP_WINDOWS_UPDATE_SOURCE STREQUAL "gitea")
  set(DESKUP_SOURCE_GITEA 1)
endif()
set(DESKUP_INCLUDE_PRERELEASES 0)
if(DESKUP_GITEA_INCLUDE_PRERELEASES)
  if(NOT DESKUP_SOURCE_GITEA)
    message(FATAL_ERROR "DESKUP_GITEA_INCLUDE_PRERELEASES requires the gitea source")
  endif()
  set(DESKUP_INCLUDE_PRERELEASES 1)
endif()
if(DESKUP_WINDOWS_UPDATE_URL AND NOT DESKUP_WINDOWS_UPDATE_URL MATCHES "^https://[A-Za-z0-9.-]+(:[0-9]+)?(/[A-Za-z0-9_./~-]*)?$")
  if(NOT DESKUP_ALLOW_LOCAL_HTTP OR NOT DESKUP_WINDOWS_UPDATE_URL MATCHES "^http://(localhost|127\\.0\\.0\\.1):[0-9]+(/[A-Za-z0-9_./~-]*)?$")
    message(FATAL_ERROR "deskup requires HTTPS; explicit local test HTTP is limited to loopback")
  endif()
endif()
# The pinned SDK constructs /api/v1/repos/<owner>/<repo> at the origin.
# Reject subpath hosting, release/API URLs and .git clone URLs early.
if(DESKUP_SOURCE_GITEA AND DESKUP_WINDOWS_UPDATE_URL)
  if(NOT DESKUP_WINDOWS_UPDATE_URL MATCHES "^https?://[^/]+/[A-Za-z0-9_.~-]+/[A-Za-z0-9_.~-]+/?$" OR DESKUP_WINDOWS_UPDATE_URL MATCHES "\\.git/?$")
    message(FATAL_ERROR "Gitea source requires an origin-root repository URL: https://host/owner/repo")
  endif()
endif()
if(DESKUP_WINDOWS_UPDATE_URL AND NOT DESKUP_UPDATE_PACKAGE_ID MATCHES "^[A-Za-z0-9][A-Za-z0-9_.-]*$")
  message(FATAL_ERROR "Set DESKUP_UPDATE_PACKAGE_ID to the Velopack package identity")
endif()
if(NOT DEFINED DESKUP_PREFERENCE_ROOT)
  set(DESKUP_PREFERENCE_ROOT "Software\\\\Deskup\\\\")
endif()
