# Pin the SDK and its archive digest so local and CI builds use the same ABI.
include("${CMAKE_CURRENT_SOURCE_DIR}/update_configuration.cmake")
set(DESKUP_VELOPACK_VERSION "1.2.161")
set(velopack_url "https://github.com/velopack/velopack/releases/download/${DESKUP_VELOPACK_VERSION}/velopack_libc_${DESKUP_VELOPACK_VERSION}.zip")
if(DEFINED ENV{DESKUP_VELOPACK_ARCHIVE})
  file(TO_CMAKE_PATH "$ENV{DESKUP_VELOPACK_ARCHIVE}" velopack_url)
endif()
include(FetchContent)
if(POLICY CMP0135)
  cmake_policy(SET CMP0135 NEW)
endif()
FetchContent_Declare(deskup_velopack
  URL "${velopack_url}"
  URL_HASH SHA256=31de8f2cf05a47bd5328a9f98b0c41aec1582156f6075f1058b26941f7f17c20
)
FetchContent_MakeAvailable(deskup_velopack)
if(FLUTTER_TARGET_PLATFORM STREQUAL "windows-arm64")
  set(velopack_arch arm64)
else()
  set(velopack_arch x64)
endif()
set(velopack_dll "${deskup_velopack_SOURCE_DIR}/lib/velopack_libc_win_${velopack_arch}_msvc.dll")
target_include_directories(${PLUGIN_NAME} PRIVATE "${deskup_velopack_SOURCE_DIR}/include")
target_link_libraries(${PLUGIN_NAME} PRIVATE "${velopack_dll}.lib" "advapi32.lib" "version.lib")
# Flutter installs bundled libraries into the application directory.
set(deskup_runtime "${CMAKE_CURRENT_BINARY_DIR}/velopack_libc.dll")
configure_file("${velopack_dll}" "${deskup_runtime}" COPYONLY)
set(deskup_bundled_libraries "${deskup_runtime}" "${CMAKE_CURRENT_SOURCE_DIR}/velopack-LICENSE.txt" PARENT_SCOPE)
configure_file("${CMAKE_CURRENT_SOURCE_DIR}/update_config.h.in" "${CMAKE_CURRENT_BINARY_DIR}/update_config.h" @ONLY)
target_include_directories(${PLUGIN_NAME} PRIVATE "${CMAKE_CURRENT_BINARY_DIR}")
